language: cpp

compiler:
    - gcc
    - clang

env:
    - BUILD_POCO=true
    - BUILD_POCO=false

os:
    - linux
    - osx

matrix:
    exclude:
    - compiler: gcc
      os: osx

before_install:
#    - echo $LANG
#    - echo $LC_ALL
    - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -qq && echo "linux platform"; fi
    - if [ $TRAVIS_OS_NAME == osx ]; then brew update && echo "osx platform"; fi

install: ./CI/travis/install_dependencies.sh

before_script:
    - mkdir build
    - cd build
    - cmake ..
    - make help

script: 
    - make -j2
    - ctest -V

