language: cpp

compiler:
    - gcc
    - clang

env:
    - BUILD_POCO=true
    - BUILD_POCO=false

os:
    - linux
    - osx

before_install:
#    - echo $LANG
#    - echo $LC_ALL
    - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -qq && echo "linux platform"; fi
    - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew doctor && echo "osx platform"; fi
    - if [ $TRAVIS_OS_NAME == osx ] && [ $CC == gcc ]; then brew install gcc && export CC=gcc-4.8; fi

install: ./CI/travis/install_dependencies.sh

before_script:
    - mkdir build
    - cd build
    - cmake ..
    - make help

script: 
    - make -j2
    - ctest -V

