language: cpp

compiler:
    - gcc
    - clang

env:
    - BUILD_POCO=true
    - BUILD_POCO=false

os:
    - linux
    - osx

matrix:
    exclude:
    - compiler: gcc
      os: osx
    - env: BUILD_POCO=false
      dist: "trusty"
      # due to regex bug in poco 1.3.6 used in trusty > failure...

before_install:
#    - echo $LANG
#    - echo $LC_ALL
    - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -qq && echo "linux platform"; fi
    - if [ $TRAVIS_OS_NAME == linux ] && [ $CC = clang ]; then export CXXFLAGS="$CXXFLAGS -std=gnu++11"; fi
    - if [ $TRAVIS_OS_NAME == osx ]; then brew update && echo "osx platform"; fi

install: ./CI/travis/install_dependencies.sh

before_script:
    - env
    - $CXX -dM -E -x c++ /dev/null
    - if [ $TRAVIS_OS_NAME == linux ]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi
    - sleep 3 # give xvfb some time to start
    - mkdir build
    - cd build
    - cmake ..
    - make help

script: 
    - make -j2
    - ctest -V

